script: uname -a
deploy:
  provider: s3
  access_key_id: $SECRET_ID
  secret_access_key: $SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  upload-dir: notes
  region: ap-chengdu
  endpoint: $S3_ENDPOINT
  dot_match: false # 除开点开头的文件
